# Generated by Django 2.2 on 2020-10-15 18:56

from django.db import migrations, models
import storages.backends.s3boto3


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0008_auto_20201016_0000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='header_image',
            field=models.ImageField(storage=storages.backends.s3boto3.S3Boto3Storage(), upload_to=''),
        ),
    ]
