# Generated by Django 2.2 on 2020-10-20 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0009_auto_20201016_0026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='header_image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cartoonify.Image'),
        ),
    ]
