# Generated by Django 2.2 on 2020-10-16 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cartoonify', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Images',
            new_name='Image',
        ),
    ]
