# Generated by Django 2.2 on 2020-10-16 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartoonify', '0002_auto_20201016_2224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='cartoonified_image',
            field=models.ImageField(upload_to='cartoonified_images'),
        ),
        migrations.AlterField(
            model_name='image',
            name='original_image',
            field=models.ImageField(upload_to='original_images'),
        ),
    ]
